version: "2"
linters:
  enable:
    - contextcheck
    - gocritic
    - gosec
    - misspell
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: .*_test.go
        text: 'G601: Implicit memory aliasing in for loop'
      - linters:
          - gosec
        path: .*_test.go
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/go-gpuallocator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
