run:
  deadline: 10m

linters:
  enable:
    - contextcheck
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/go-gpuallocator

issues:
  exclude-rules:
  # We disable the memory aliasing checks in tests
  - path: ".*_test.go"
    linters:
    - gosec
    text: "G601: Implicit memory aliasing in for loop"
  # We create world-readable files in tests.
  - path: ".*_test.go"
    linters:
    - gosec
    text: "G306: Expect WriteFile permissions to be 0600 or less"