// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package nvml

import ()

// Ensure, that DeviceMock does implement Device.
// If this is not the case, regenerate this file with moq.
var _ Device = &DeviceMock{}

// DeviceMock is a mock implementation of Device.
//
// 	func TestSomethingThatUsesDevice(t *testing.T) {
//
// 		// make and configure a mocked Device
// 		mockedDevice := &DeviceMock{
// 		}
//
// 		// use mockedDevice in code that requires Device
// 		// and then make assertions.
//
// 	}
type DeviceMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
